// LoginPage/style.js
export const styles = {
  wrapper: {
    minHeight: "100vh",
    backgroundRepeat: "no-repeat",
    backgroundSize: "cover",
    backgroundPosition: "center",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  card: {
    width: 400,
    borderRadius: 16,
    overflow: "hidden",
    background: "#fff",
    boxShadow: "0 20px 50px rgba(0,0,0,0.4)",
  },
  topSection: {
    background: "linear-gradient(to top right, #6a1b9a, #e040fb)",
    color: "#fff",
    padding: "30px 24px 40px",
    position: "relative",
    textAlign: "center",
  },
  decorImage: {
    position: "absolute",
    top: 0,
    left: 0,
    width: "100%",
    height: "100%",
    objectFit: "cover",
    opacity: 0.1,
    pointerEvents: "none",
    zIndex: 0,
  },
  title: {
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 8,
    position: "relative",
    zIndex: 1,
  },
  desc: {
    fontSize: 12,
    opacity: 0.9,
    position: "relative",
    zIndex: 1,
    marginBottom: 10,
  },
  link: {
    position: "absolute",
    top: 16,
    right: 24,
    fontSize: 13,
    color: "#fff",
    textDecoration: "underline",
    zIndex: 2,
  },
  body: {
    padding: "28px 24px 32px",
    background: "#fff",
  },
  sectionTitle: {
    textAlign: "center",
    color: "#6a1b9a",
    fontWeight: "bold",
    marginBottom: 24,
  },
  inputGroup: {
    display: "flex",
    alignItems: "center",
    background: "#f3e5f5",
    borderRadius: 8,
    padding: "10px 14px",
    marginBottom: 16,
    position: "relative",
    zIndex: 1,
  },
  icon: {
    marginRight: 10,
    color: "#6a1b9a",
    fontSize: 14,
  },
  input: {
    border: "none",
    outline: "none",
    background: "transparent",
    fontSize: 14,
    width: "100%",
  },
  row: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    fontSize: 13,
    marginBottom: 16,
  },
  remember: {
    display: "flex",
    gap: 5,
    alignItems: "center",
  },
  forgot: {
    color: "#6a1b9a",
    fontSize: 12,
    textDecoration: "none",
  },
  button: {
    width: "100%",
    background: "linear-gradient(to right, #6a1b9a, #4a148c)",
    color: "#fff",
    padding: "12px 0",
    borderRadius: 8,
    fontWeight: "bold",
    fontSize: 14,
    border: "none",
    cursor: "pointer",
  },
};
